export const siteConfig = {
  name: "Techlogs",
  title: "Techlogs - Blog Technologique",
  description: "Explorez les dernières tendances en technologie, développement web et innovation digitale",
  author: "Techlogs Team",
  email: "contact@techlogs.blog",
  url: "https://tech-logs.vercel.app",
  language: "fr",
  locale: "fr_FR",
  ogImage: "/og-image.png",
  links: {
    twitter: "https://twitter.com",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
  },
  categories: [
    { slug: "web-dev", name: "Développement Web", icon: "Code" },
    { slug: "ia", name: "Intelligence Artificielle", icon: "Brain" },
    { slug: "devops", name: "DevOps & Infrastructure", icon: "Server" },
    { slug: "securite", name: "Sécurité", icon: "Shield" },
    { slug: "mobile", name: "Développement Mobile", icon: "Smartphone" },
    { slug: "cloud", name: "Cloud Computing", icon: "Cloud" },
    { slug: "blockchain", name: "Blockchain & Web3", icon: "Link" },
    { slug: "iot", name: "IoT & Objets Connectés", icon: "Cpu" },
    { slug: "data-science", name: "Data Science", icon: "BarChart" },
  ],
}
